/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package uk_co_real_logic_sbe_ir_generated

import (
"errors"
"fmt"
)

type ByteOrderCodec uint8
    const (
    ByteOrderCodec_SBE_LITTLE_ENDIAN ByteOrderCodec = ByteOrderCodec(uint8(0))
    ByteOrderCodec_SBE_BIG_ENDIAN ByteOrderCodec = ByteOrderCodec(uint8(1))
    ByteOrderCodec_NULL_VALUE ByteOrderCodec = ByteOrderCodec(uint8(255))

    )

    var ByteOrderCodecLookupErr = errors.New("unknown value for enum ByteOrderCodec [E103]")
    func LookupByteOrderCodec(value uint8) (ByteOrderCodec, error) {
        switch value {
            case uint8(0): return ByteOrderCodec_SBE_LITTLE_ENDIAN, nil
            case uint8(1): return ByteOrderCodec_SBE_BIG_ENDIAN, nil
            case uint8(255): return ByteOrderCodec_NULL_VALUE, nil
        }

        return 0, ByteOrderCodecLookupErr
}

    func (value ByteOrderCodec) String() string {
        switch value {
            case ByteOrderCodec_SBE_LITTLE_ENDIAN: return "SBE_LITTLE_ENDIAN"
            case ByteOrderCodec_SBE_BIG_ENDIAN: return "SBE_BIG_ENDIAN"
            case ByteOrderCodec_NULL_VALUE: return "NULL_VALUE"
        }

        panic(fmt.Sprintf("unknown value for enum ByteOrderCodec [E103]: %d", value))
    }


