/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package uk_co_real_logic_sbe_ir_generated

import (
"fmt"
"strings"
)

type FrameCodec struct {
    buffer []byte
    bufferLength uint64
    offset uint64
    position uint64
    actingBlockLength uint64
    actingVersion uint64
}

    func (m *FrameCodec) sbePositionPtr() *uint64 {
        return &m.position
    }

    const (
        FrameCodecSbeBlockLength     uint16 = uint16(12)
        FrameCodecSbeTemplateID      uint16 = uint16(1)
        FrameCodecSbeSchemaID        uint16 = uint16(1)
        FrameCodecSbeSchemaVersion   uint16 = uint16(0)
        FrameCodecSbeSemanticVersion string = ""
    )

    func (m *FrameCodec) SbeBlockLength() uint16 {
        return uint16(12)
    }

    func (m *FrameCodec) SbeBlockAndHeaderLength() uint64 {
        return MessageHeaderEncodedLength + uint64(m.SbeBlockLength())
    }

    func (m *FrameCodec) SbeTemplateId() uint16 {
        return uint16(1)
    }

    func (m *FrameCodec) SbeSchemaId() uint16 {
        return uint16(1)
    }

    func (m *FrameCodec) SbeSchemaVersion() uint16 {
        return uint16(0)
    }

    func (m *FrameCodec) SbeSemanticVersion() string {
        return ""
    }

    func (m *FrameCodec) SbeSemanticType() string {
        return ""
    }

    func (m *FrameCodec) Offset() uint64 {
        return m.offset
    }

    func (m *FrameCodec) Wrap(
        buffer []byte,
        offset uint64,
        bufferLength uint64,
        actingBlockLength uint64,
        actingVersion uint64) *FrameCodec {
        m.buffer = buffer
        m.bufferLength = bufferLength
        m.offset = offset
        m.position = m.SbeCheckPosition(offset + actingBlockLength)
        m.actingBlockLength = actingBlockLength
        m.actingVersion = actingVersion
        return m
    }

    func (m *FrameCodec) WrapForEncode(buffer []byte, offset uint64, bufferLength uint64) *FrameCodec {
        return m.Wrap(buffer, offset, bufferLength,
            uint64(m.SbeBlockLength()), uint64(m.SbeSchemaVersion()))
    }

    func (m *FrameCodec) WrapAndApplyHeader(buffer []byte, offset uint64, bufferLength uint64) *FrameCodec {
        var hdr MessageHeader
        hdr.Wrap(buffer, offset, uint64(m.SbeSchemaVersion()), bufferLength)

        hdr.SetBlockLength(m.SbeBlockLength()).
           SetTemplateId(m.SbeTemplateId()).
           SetSchemaId(m.SbeSchemaId()).
           SetVersion(m.SbeSchemaVersion())

        return m.Wrap(
            buffer,
            offset + hdr.EncodedLength(),
            bufferLength,
            uint64(m.SbeBlockLength()),
            uint64(m.SbeSchemaVersion()))
    }

    func (m *FrameCodec) WrapForDecode(
        buffer []byte,
        offset uint64,
        actingBlockLength uint64,
        actingVersion uint64,
        bufferLength uint64) *FrameCodec {
        return m.Wrap(
            buffer,
            offset,
            bufferLength,
            actingBlockLength,
            actingVersion)
    }

    func (m *FrameCodec) sbeRewind() *FrameCodec {
        return m.WrapForDecode(m.buffer, m.offset, m.actingBlockLength, m.actingVersion, m.bufferLength)
    }

    func (m *FrameCodec) SbePosition() uint64 {
        return m.position
    }

    func (m *FrameCodec) SbeCheckPosition(position uint64) uint64 {
        if !SbeNoBoundsCheck && (position > m.bufferLength) {
            panic("buffer too short [E100]")
        }
        return position
    }

    func (m *FrameCodec) SetSbePosition(position uint64) {
        m.position = m.SbeCheckPosition(position)
    }

    func (m *FrameCodec) EncodedLength() uint64 {
        return m.SbePosition() - m.offset
    }

    func (m *FrameCodec) DecodeLength() uint64 {
        var skipper FrameCodec
        skipper.WrapForDecode(m.buffer, m.offset, uint64(m.SbeBlockLength()),
            uint64(m.ActingVersion()), m.bufferLength)
        skipper.Skip()
        return skipper.EncodedLength()
    }

    func (m *FrameCodec) Buffer() []byte {
        return m.buffer
    }

    func (m *FrameCodec) BufferLength() uint64 {
        return m.bufferLength
    }

    func (m *FrameCodec) ActingVersion() uint64 {
        return m.actingVersion
    }

func (m *FrameCodec) IrIdMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *FrameCodec) IrIdId() int {
        return 1
    }

    func (m *FrameCodec) IrIdSinceVersion() uint64 {
        return 0
    }

    func (m *FrameCodec) IrIdInActingVersion() bool {
        return true
    }

    func (m *FrameCodec) IrIdEncodingOffset() uint {
        return 0
    }

    func (m *FrameCodec) IrIdNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *FrameCodec) IrIdMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *FrameCodec) IrIdMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *FrameCodec) IrIdEncodingLength() int {
        return 4
    }

    func (m *FrameCodec) IrId() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 0):])
    }

    func (m *FrameCodec) SetIrId(value int32) *FrameCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 0):], value)
        return m
    }

func (m *FrameCodec) IrVersionMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *FrameCodec) IrVersionId() int {
        return 2
    }

    func (m *FrameCodec) IrVersionSinceVersion() uint64 {
        return 0
    }

    func (m *FrameCodec) IrVersionInActingVersion() bool {
        return true
    }

    func (m *FrameCodec) IrVersionEncodingOffset() uint {
        return 4
    }

    func (m *FrameCodec) IrVersionNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *FrameCodec) IrVersionMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *FrameCodec) IrVersionMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *FrameCodec) IrVersionEncodingLength() int {
        return 4
    }

    func (m *FrameCodec) IrVersion() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 4):])
    }

    func (m *FrameCodec) SetIrVersion(value int32) *FrameCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 4):], value)
        return m
    }

func (m *FrameCodec) SchemaVersionMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *FrameCodec) SchemaVersionId() int {
        return 3
    }

    func (m *FrameCodec) SchemaVersionSinceVersion() uint64 {
        return 0
    }

    func (m *FrameCodec) SchemaVersionInActingVersion() bool {
        return true
    }

    func (m *FrameCodec) SchemaVersionEncodingOffset() uint {
        return 8
    }

    func (m *FrameCodec) SchemaVersionNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *FrameCodec) SchemaVersionMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *FrameCodec) SchemaVersionMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *FrameCodec) SchemaVersionEncodingLength() int {
        return 4
    }

    func (m *FrameCodec) SchemaVersion() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 8):])
    }

    func (m *FrameCodec) SetSchemaVersion(value int32) *FrameCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 8):], value)
        return m
    }

func (m *FrameCodec) PackageNameMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *FrameCodec) PackageNameCharacterEncoding() string {
        return "UTF-8"
    }

func (m *FrameCodec) PackageNameSinceVersion() uint64 {
        return 0
    }

func (m *FrameCodec) PackageNameInActingVersion() bool {
        return true
    }

func (m *FrameCodec) PackageNameId() uint16 {
        return 4
    }

func (m *FrameCodec) PackageNameHeaderLength() uint64 {
        return 2
}

func (m *FrameCodec) PackageNameLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *FrameCodec) SkipPackageName() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *FrameCodec) PackageName() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *FrameCodec) GetPackageName(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *FrameCodec) PutPackageNameLen(src string, length uint16) *FrameCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *FrameCodec) GetPackageNameAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *FrameCodec) GetPackageNameAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetPackageNameAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *FrameCodec) PutPackageName(str string) *FrameCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutPackageNameLen(str, uint16(len(str)))
}

func (m *FrameCodec) NamespaceNameMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *FrameCodec) NamespaceNameCharacterEncoding() string {
        return "UTF-8"
    }

func (m *FrameCodec) NamespaceNameSinceVersion() uint64 {
        return 0
    }

func (m *FrameCodec) NamespaceNameInActingVersion() bool {
        return true
    }

func (m *FrameCodec) NamespaceNameId() uint16 {
        return 5
    }

func (m *FrameCodec) NamespaceNameHeaderLength() uint64 {
        return 2
}

func (m *FrameCodec) NamespaceNameLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *FrameCodec) SkipNamespaceName() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *FrameCodec) NamespaceName() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *FrameCodec) GetNamespaceName(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *FrameCodec) PutNamespaceNameLen(src string, length uint16) *FrameCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *FrameCodec) GetNamespaceNameAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *FrameCodec) GetNamespaceNameAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetNamespaceNameAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *FrameCodec) PutNamespaceName(str string) *FrameCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutNamespaceNameLen(str, uint16(len(str)))
}

func (m *FrameCodec) SemanticVersionMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *FrameCodec) SemanticVersionCharacterEncoding() string {
        return "UTF-8"
    }

func (m *FrameCodec) SemanticVersionSinceVersion() uint64 {
        return 0
    }

func (m *FrameCodec) SemanticVersionInActingVersion() bool {
        return true
    }

func (m *FrameCodec) SemanticVersionId() uint16 {
        return 6
    }

func (m *FrameCodec) SemanticVersionHeaderLength() uint64 {
        return 2
}

func (m *FrameCodec) SemanticVersionLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *FrameCodec) SkipSemanticVersion() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *FrameCodec) SemanticVersion() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *FrameCodec) GetSemanticVersion(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *FrameCodec) PutSemanticVersionLen(src string, length uint16) *FrameCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *FrameCodec) GetSemanticVersionAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *FrameCodec) GetSemanticVersionAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetSemanticVersionAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *FrameCodec) PutSemanticVersion(str string) *FrameCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutSemanticVersionLen(str, uint16(len(str)))
}

func (writer *FrameCodec) String() string {
    var builder strings.Builder
    builder.WriteString("{\"Name\": \"FrameCodec\", ")
    builder.WriteString(fmt.Sprintf("\"sbeTemplateId\": %d", writer.SbeTemplateId()))
    builder.WriteString(", ")

    builder.WriteString(`"irId": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.IrId()))

    builder.WriteString(", ")
    builder.WriteString(`"irVersion": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.IrVersion()))

    builder.WriteString(", ")
    builder.WriteString(`"schemaVersion": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.SchemaVersion()))

    builder.WriteString(", ")
    builder.WriteString(`"packageName": `)
    builder.WriteString(`"` + writer.GetPackageNameAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"namespaceName": `)
    builder.WriteString(`"` + writer.GetNamespaceNameAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"semanticVersion": `)
    builder.WriteString(`"` + writer.GetSemanticVersionAsJsonEscapedString() + `"`);

    builder.WriteString("}")

    return builder.String()
}

func (m *FrameCodec) Skip() {
    m.SkipPackageName()
    m.SkipNamespaceName()
    m.SkipSemanticVersion()
}

func (m *FrameCodec) IsConstLength() bool {
    return false
}

func (m *FrameCodec) ComputeLength(
     PackageNameLength int,
     NamespaceNameLength int,
     SemanticVersionLength int) (int, error) {
    length := uint64(m.SbeBlockLength())

    length += m.PackageNameHeaderLength()
    if m.PackageNameLength() > 65534 {
        return 0, fmt.Errorf("PackageNameLength too long for length type [E109]")
    }
    length += uint64(m.PackageNameLength())

    length += m.NamespaceNameHeaderLength()
    if m.NamespaceNameLength() > 65534 {
        return 0, fmt.Errorf("NamespaceNameLength too long for length type [E109]")
    }
    length += uint64(m.NamespaceNameLength())

    length += m.SemanticVersionHeaderLength()
    if m.SemanticVersionLength() > 65534 {
        return 0, fmt.Errorf("SemanticVersionLength too long for length type [E109]")
    }
    length += uint64(m.SemanticVersionLength())

    return int(length), nil
}
