/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package uk_co_real_logic_sbe_ir_generated

import (
"errors"
"fmt"
)

type PresenceCodec uint8
    const (
    PresenceCodec_SBE_REQUIRED PresenceCodec = PresenceCodec(uint8(0))
    PresenceCodec_SBE_OPTIONAL PresenceCodec = PresenceCodec(uint8(1))
    PresenceCodec_SBE_CONSTANT PresenceCodec = PresenceCodec(uint8(2))
    PresenceCodec_NULL_VALUE PresenceCodec = PresenceCodec(uint8(255))

    )

    var PresenceCodecLookupErr = errors.New("unknown value for enum PresenceCodec [E103]")
    func LookupPresenceCodec(value uint8) (PresenceCodec, error) {
        switch value {
            case uint8(0): return PresenceCodec_SBE_REQUIRED, nil
            case uint8(1): return PresenceCodec_SBE_OPTIONAL, nil
            case uint8(2): return PresenceCodec_SBE_CONSTANT, nil
            case uint8(255): return PresenceCodec_NULL_VALUE, nil
        }

        return 0, PresenceCodecLookupErr
}

    func (value PresenceCodec) String() string {
        switch value {
            case PresenceCodec_SBE_REQUIRED: return "SBE_REQUIRED"
            case PresenceCodec_SBE_OPTIONAL: return "SBE_OPTIONAL"
            case PresenceCodec_SBE_CONSTANT: return "SBE_CONSTANT"
            case PresenceCodec_NULL_VALUE: return "NULL_VALUE"
        }

        panic(fmt.Sprintf("unknown value for enum PresenceCodec [E103]: %d", value))
    }


