/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package uk_co_real_logic_sbe_ir_generated

import (
"errors"
"fmt"
)

type PrimitiveTypeCodec uint8
    const (
    PrimitiveTypeCodec_NONE PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(0))
    PrimitiveTypeCodec_CHAR PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(1))
    PrimitiveTypeCodec_INT8 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(2))
    PrimitiveTypeCodec_INT16 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(3))
    PrimitiveTypeCodec_INT32 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(4))
    PrimitiveTypeCodec_INT64 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(5))
    PrimitiveTypeCodec_UINT8 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(6))
    PrimitiveTypeCodec_UINT16 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(7))
    PrimitiveTypeCodec_UINT32 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(8))
    PrimitiveTypeCodec_UINT64 PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(9))
    PrimitiveTypeCodec_FLOAT PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(10))
    PrimitiveTypeCodec_DOUBLE PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(11))
    PrimitiveTypeCodec_NULL_VALUE PrimitiveTypeCodec = PrimitiveTypeCodec(uint8(255))

    )

    var PrimitiveTypeCodecLookupErr = errors.New("unknown value for enum PrimitiveTypeCodec [E103]")
    func LookupPrimitiveTypeCodec(value uint8) (PrimitiveTypeCodec, error) {
        switch value {
            case uint8(0): return PrimitiveTypeCodec_NONE, nil
            case uint8(1): return PrimitiveTypeCodec_CHAR, nil
            case uint8(2): return PrimitiveTypeCodec_INT8, nil
            case uint8(3): return PrimitiveTypeCodec_INT16, nil
            case uint8(4): return PrimitiveTypeCodec_INT32, nil
            case uint8(5): return PrimitiveTypeCodec_INT64, nil
            case uint8(6): return PrimitiveTypeCodec_UINT8, nil
            case uint8(7): return PrimitiveTypeCodec_UINT16, nil
            case uint8(8): return PrimitiveTypeCodec_UINT32, nil
            case uint8(9): return PrimitiveTypeCodec_UINT64, nil
            case uint8(10): return PrimitiveTypeCodec_FLOAT, nil
            case uint8(11): return PrimitiveTypeCodec_DOUBLE, nil
            case uint8(255): return PrimitiveTypeCodec_NULL_VALUE, nil
        }

        return 0, PrimitiveTypeCodecLookupErr
}

    func (value PrimitiveTypeCodec) String() string {
        switch value {
            case PrimitiveTypeCodec_NONE: return "NONE"
            case PrimitiveTypeCodec_CHAR: return "CHAR"
            case PrimitiveTypeCodec_INT8: return "INT8"
            case PrimitiveTypeCodec_INT16: return "INT16"
            case PrimitiveTypeCodec_INT32: return "INT32"
            case PrimitiveTypeCodec_INT64: return "INT64"
            case PrimitiveTypeCodec_UINT8: return "UINT8"
            case PrimitiveTypeCodec_UINT16: return "UINT16"
            case PrimitiveTypeCodec_UINT32: return "UINT32"
            case PrimitiveTypeCodec_UINT64: return "UINT64"
            case PrimitiveTypeCodec_FLOAT: return "FLOAT"
            case PrimitiveTypeCodec_DOUBLE: return "DOUBLE"
            case PrimitiveTypeCodec_NULL_VALUE: return "NULL_VALUE"
        }

        panic(fmt.Sprintf("unknown value for enum PrimitiveTypeCodec [E103]: %d", value))
    }


