/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package uk_co_real_logic_sbe_ir_generated

import (
"errors"
"fmt"
)

type SignalCodec uint8
    const (
    SignalCodec_BEGIN_MESSAGE SignalCodec = SignalCodec(uint8(1))
    SignalCodec_END_MESSAGE SignalCodec = SignalCodec(uint8(2))
    SignalCodec_BEGIN_COMPOSITE SignalCodec = SignalCodec(uint8(3))
    SignalCodec_END_COMPOSITE SignalCodec = SignalCodec(uint8(4))
    SignalCodec_BEGIN_FIELD SignalCodec = SignalCodec(uint8(5))
    SignalCodec_END_FIELD SignalCodec = SignalCodec(uint8(6))
    SignalCodec_BEGIN_GROUP SignalCodec = SignalCodec(uint8(7))
    SignalCodec_END_GROUP SignalCodec = SignalCodec(uint8(8))
    SignalCodec_BEGIN_ENUM SignalCodec = SignalCodec(uint8(9))
    SignalCodec_VALID_VALUE SignalCodec = SignalCodec(uint8(10))
    SignalCodec_END_ENUM SignalCodec = SignalCodec(uint8(11))
    SignalCodec_BEGIN_SET SignalCodec = SignalCodec(uint8(12))
    SignalCodec_CHOICE SignalCodec = SignalCodec(uint8(13))
    SignalCodec_END_SET SignalCodec = SignalCodec(uint8(14))
    SignalCodec_BEGIN_VAR_DATA SignalCodec = SignalCodec(uint8(15))
    SignalCodec_END_VAR_DATA SignalCodec = SignalCodec(uint8(16))
    SignalCodec_ENCODING SignalCodec = SignalCodec(uint8(17))
    SignalCodec_NULL_VALUE SignalCodec = SignalCodec(uint8(255))

    )

    var SignalCodecLookupErr = errors.New("unknown value for enum SignalCodec [E103]")
    func LookupSignalCodec(value uint8) (SignalCodec, error) {
        switch value {
            case uint8(1): return SignalCodec_BEGIN_MESSAGE, nil
            case uint8(2): return SignalCodec_END_MESSAGE, nil
            case uint8(3): return SignalCodec_BEGIN_COMPOSITE, nil
            case uint8(4): return SignalCodec_END_COMPOSITE, nil
            case uint8(5): return SignalCodec_BEGIN_FIELD, nil
            case uint8(6): return SignalCodec_END_FIELD, nil
            case uint8(7): return SignalCodec_BEGIN_GROUP, nil
            case uint8(8): return SignalCodec_END_GROUP, nil
            case uint8(9): return SignalCodec_BEGIN_ENUM, nil
            case uint8(10): return SignalCodec_VALID_VALUE, nil
            case uint8(11): return SignalCodec_END_ENUM, nil
            case uint8(12): return SignalCodec_BEGIN_SET, nil
            case uint8(13): return SignalCodec_CHOICE, nil
            case uint8(14): return SignalCodec_END_SET, nil
            case uint8(15): return SignalCodec_BEGIN_VAR_DATA, nil
            case uint8(16): return SignalCodec_END_VAR_DATA, nil
            case uint8(17): return SignalCodec_ENCODING, nil
            case uint8(255): return SignalCodec_NULL_VALUE, nil
        }

        return 0, SignalCodecLookupErr
}

    func (value SignalCodec) String() string {
        switch value {
            case SignalCodec_BEGIN_MESSAGE: return "BEGIN_MESSAGE"
            case SignalCodec_END_MESSAGE: return "END_MESSAGE"
            case SignalCodec_BEGIN_COMPOSITE: return "BEGIN_COMPOSITE"
            case SignalCodec_END_COMPOSITE: return "END_COMPOSITE"
            case SignalCodec_BEGIN_FIELD: return "BEGIN_FIELD"
            case SignalCodec_END_FIELD: return "END_FIELD"
            case SignalCodec_BEGIN_GROUP: return "BEGIN_GROUP"
            case SignalCodec_END_GROUP: return "END_GROUP"
            case SignalCodec_BEGIN_ENUM: return "BEGIN_ENUM"
            case SignalCodec_VALID_VALUE: return "VALID_VALUE"
            case SignalCodec_END_ENUM: return "END_ENUM"
            case SignalCodec_BEGIN_SET: return "BEGIN_SET"
            case SignalCodec_CHOICE: return "CHOICE"
            case SignalCodec_END_SET: return "END_SET"
            case SignalCodec_BEGIN_VAR_DATA: return "BEGIN_VAR_DATA"
            case SignalCodec_END_VAR_DATA: return "END_VAR_DATA"
            case SignalCodec_ENCODING: return "ENCODING"
            case SignalCodec_NULL_VALUE: return "NULL_VALUE"
        }

        panic(fmt.Sprintf("unknown value for enum SignalCodec [E103]: %d", value))
    }


