/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package uk_co_real_logic_sbe_ir_generated

import (
"fmt"
"strings"
)

type TokenCodec struct {
    buffer []byte
    bufferLength uint64
    offset uint64
    position uint64
    actingBlockLength uint64
    actingVersion uint64
}

    func (m *TokenCodec) sbePositionPtr() *uint64 {
        return &m.position
    }

    const (
        TokenCodecSbeBlockLength     uint16 = uint16(28)
        TokenCodecSbeTemplateID      uint16 = uint16(2)
        TokenCodecSbeSchemaID        uint16 = uint16(1)
        TokenCodecSbeSchemaVersion   uint16 = uint16(0)
        TokenCodecSbeSemanticVersion string = ""
    )

    func (m *TokenCodec) SbeBlockLength() uint16 {
        return uint16(28)
    }

    func (m *TokenCodec) SbeBlockAndHeaderLength() uint64 {
        return MessageHeaderEncodedLength + uint64(m.SbeBlockLength())
    }

    func (m *TokenCodec) SbeTemplateId() uint16 {
        return uint16(2)
    }

    func (m *TokenCodec) SbeSchemaId() uint16 {
        return uint16(1)
    }

    func (m *TokenCodec) SbeSchemaVersion() uint16 {
        return uint16(0)
    }

    func (m *TokenCodec) SbeSemanticVersion() string {
        return ""
    }

    func (m *TokenCodec) SbeSemanticType() string {
        return ""
    }

    func (m *TokenCodec) Offset() uint64 {
        return m.offset
    }

    func (m *TokenCodec) Wrap(
        buffer []byte,
        offset uint64,
        bufferLength uint64,
        actingBlockLength uint64,
        actingVersion uint64) *TokenCodec {
        m.buffer = buffer
        m.bufferLength = bufferLength
        m.offset = offset
        m.position = m.SbeCheckPosition(offset + actingBlockLength)
        m.actingBlockLength = actingBlockLength
        m.actingVersion = actingVersion
        return m
    }

    func (m *TokenCodec) WrapForEncode(buffer []byte, offset uint64, bufferLength uint64) *TokenCodec {
        return m.Wrap(buffer, offset, bufferLength,
            uint64(m.SbeBlockLength()), uint64(m.SbeSchemaVersion()))
    }

    func (m *TokenCodec) WrapAndApplyHeader(buffer []byte, offset uint64, bufferLength uint64) *TokenCodec {
        var hdr MessageHeader
        hdr.Wrap(buffer, offset, uint64(m.SbeSchemaVersion()), bufferLength)

        hdr.SetBlockLength(m.SbeBlockLength()).
           SetTemplateId(m.SbeTemplateId()).
           SetSchemaId(m.SbeSchemaId()).
           SetVersion(m.SbeSchemaVersion())

        return m.Wrap(
            buffer,
            offset + hdr.EncodedLength(),
            bufferLength,
            uint64(m.SbeBlockLength()),
            uint64(m.SbeSchemaVersion()))
    }

    func (m *TokenCodec) WrapForDecode(
        buffer []byte,
        offset uint64,
        actingBlockLength uint64,
        actingVersion uint64,
        bufferLength uint64) *TokenCodec {
        return m.Wrap(
            buffer,
            offset,
            bufferLength,
            actingBlockLength,
            actingVersion)
    }

    func (m *TokenCodec) sbeRewind() *TokenCodec {
        return m.WrapForDecode(m.buffer, m.offset, m.actingBlockLength, m.actingVersion, m.bufferLength)
    }

    func (m *TokenCodec) SbePosition() uint64 {
        return m.position
    }

    func (m *TokenCodec) SbeCheckPosition(position uint64) uint64 {
        if !SbeNoBoundsCheck && (position > m.bufferLength) {
            panic("buffer too short [E100]")
        }
        return position
    }

    func (m *TokenCodec) SetSbePosition(position uint64) {
        m.position = m.SbeCheckPosition(position)
    }

    func (m *TokenCodec) EncodedLength() uint64 {
        return m.SbePosition() - m.offset
    }

    func (m *TokenCodec) DecodeLength() uint64 {
        var skipper TokenCodec
        skipper.WrapForDecode(m.buffer, m.offset, uint64(m.SbeBlockLength()),
            uint64(m.ActingVersion()), m.bufferLength)
        skipper.Skip()
        return skipper.EncodedLength()
    }

    func (m *TokenCodec) Buffer() []byte {
        return m.buffer
    }

    func (m *TokenCodec) BufferLength() uint64 {
        return m.bufferLength
    }

    func (m *TokenCodec) ActingVersion() uint64 {
        return m.actingVersion
    }

func (m *TokenCodec) TokenOffsetMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) TokenOffsetId() int {
        return 1
    }

    func (m *TokenCodec) TokenOffsetSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) TokenOffsetInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) TokenOffsetEncodingOffset() uint {
        return 0
    }

    func (m *TokenCodec) TokenOffsetNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *TokenCodec) TokenOffsetMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *TokenCodec) TokenOffsetMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *TokenCodec) TokenOffsetEncodingLength() int {
        return 4
    }

    func (m *TokenCodec) TokenOffset() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 0):])
    }

    func (m *TokenCodec) SetTokenOffset(value int32) *TokenCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 0):], value)
        return m
    }

func (m *TokenCodec) TokenSizeMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) TokenSizeId() int {
        return 2
    }

    func (m *TokenCodec) TokenSizeSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) TokenSizeInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) TokenSizeEncodingOffset() uint {
        return 4
    }

    func (m *TokenCodec) TokenSizeNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *TokenCodec) TokenSizeMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *TokenCodec) TokenSizeMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *TokenCodec) TokenSizeEncodingLength() int {
        return 4
    }

    func (m *TokenCodec) TokenSize() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 4):])
    }

    func (m *TokenCodec) SetTokenSize(value int32) *TokenCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 4):], value)
        return m
    }

func (m *TokenCodec) FieldIdMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) FieldIdId() int {
        return 3
    }

    func (m *TokenCodec) FieldIdSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) FieldIdInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) FieldIdEncodingOffset() uint {
        return 8
    }

    func (m *TokenCodec) FieldIdNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *TokenCodec) FieldIdMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *TokenCodec) FieldIdMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *TokenCodec) FieldIdEncodingLength() int {
        return 4
    }

    func (m *TokenCodec) FieldId() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 8):])
    }

    func (m *TokenCodec) SetFieldId(value int32) *TokenCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 8):], value)
        return m
    }

func (m *TokenCodec) TokenVersionMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) TokenVersionId() int {
        return 4
    }

    func (m *TokenCodec) TokenVersionSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) TokenVersionInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) TokenVersionEncodingOffset() uint {
        return 12
    }

    func (m *TokenCodec) TokenVersionNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *TokenCodec) TokenVersionMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *TokenCodec) TokenVersionMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *TokenCodec) TokenVersionEncodingLength() int {
        return 4
    }

    func (m *TokenCodec) TokenVersion() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 12):])
    }

    func (m *TokenCodec) SetTokenVersion(value int32) *TokenCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 12):], value)
        return m
    }

func (m *TokenCodec) ComponentTokenCountMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) ComponentTokenCountId() int {
        return 5
    }

    func (m *TokenCodec) ComponentTokenCountSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) ComponentTokenCountInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) ComponentTokenCountEncodingOffset() uint {
        return 16
    }

    func (m *TokenCodec) ComponentTokenCountNullValue() int32 {
        return SbeNullValueInt32()
    }

    func (m *TokenCodec) ComponentTokenCountMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *TokenCodec) ComponentTokenCountMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *TokenCodec) ComponentTokenCountEncodingLength() int {
        return 4
    }

    func (m *TokenCodec) ComponentTokenCount() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 16):])
    }

    func (m *TokenCodec) SetComponentTokenCount(value int32) *TokenCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 16):], value)
        return m
    }

func (m *TokenCodec) SignalMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) SignalId() int {
        return 6
    }

    func (m *TokenCodec) SignalSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) SignalInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) SignalEncodingOffset() uint {
        return 20
    }

    func (m *TokenCodec) SignalEncodingLength() int {
        return 1
    }

    func (m *TokenCodec) SignalRaw() uint8 {
        return Uint8LittleEndian(m.buffer[(m.offset + 20):])
    }

    func (m *TokenCodec) Signal() SignalCodec {
        return SignalCodec(Uint8LittleEndian(m.buffer[(m.offset + 20):]))
    }

    func (m *TokenCodec) SetSignal(value SignalCodec) *TokenCodec {
        val := uint8(value)
        PutUint8LittleEndian(m.buffer[(m.offset + 20):], val)
        return m
    }

func (m *TokenCodec) PrimitiveTypeMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) PrimitiveTypeId() int {
        return 7
    }

    func (m *TokenCodec) PrimitiveTypeSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) PrimitiveTypeInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) PrimitiveTypeEncodingOffset() uint {
        return 21
    }

    func (m *TokenCodec) PrimitiveTypeEncodingLength() int {
        return 1
    }

    func (m *TokenCodec) PrimitiveTypeRaw() uint8 {
        return Uint8LittleEndian(m.buffer[(m.offset + 21):])
    }

    func (m *TokenCodec) PrimitiveType() PrimitiveTypeCodec {
        return PrimitiveTypeCodec(Uint8LittleEndian(m.buffer[(m.offset + 21):]))
    }

    func (m *TokenCodec) SetPrimitiveType(value PrimitiveTypeCodec) *TokenCodec {
        val := uint8(value)
        PutUint8LittleEndian(m.buffer[(m.offset + 21):], val)
        return m
    }

func (m *TokenCodec) ByteOrderMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) ByteOrderId() int {
        return 8
    }

    func (m *TokenCodec) ByteOrderSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) ByteOrderInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) ByteOrderEncodingOffset() uint {
        return 22
    }

    func (m *TokenCodec) ByteOrderEncodingLength() int {
        return 1
    }

    func (m *TokenCodec) ByteOrderRaw() uint8 {
        return Uint8LittleEndian(m.buffer[(m.offset + 22):])
    }

    func (m *TokenCodec) ByteOrder() ByteOrderCodec {
        return ByteOrderCodec(Uint8LittleEndian(m.buffer[(m.offset + 22):]))
    }

    func (m *TokenCodec) SetByteOrder(value ByteOrderCodec) *TokenCodec {
        val := uint8(value)
        PutUint8LittleEndian(m.buffer[(m.offset + 22):], val)
        return m
    }

func (m *TokenCodec) PresenceMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *TokenCodec) PresenceId() int {
        return 9
    }

    func (m *TokenCodec) PresenceSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) PresenceInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) PresenceEncodingOffset() uint {
        return 23
    }

    func (m *TokenCodec) PresenceEncodingLength() int {
        return 1
    }

    func (m *TokenCodec) PresenceRaw() uint8 {
        return Uint8LittleEndian(m.buffer[(m.offset + 23):])
    }

    func (m *TokenCodec) Presence() PresenceCodec {
        return PresenceCodec(Uint8LittleEndian(m.buffer[(m.offset + 23):]))
    }

    func (m *TokenCodec) SetPresence(value PresenceCodec) *TokenCodec {
        val := uint8(value)
        PutUint8LittleEndian(m.buffer[(m.offset + 23):], val)
        return m
    }

func (m *TokenCodec) DeprecatedMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "optional"
        default: return ""
    }
}

    func (m *TokenCodec) DeprecatedId() int {
        return 10
    }

    func (m *TokenCodec) DeprecatedSinceVersion() uint64 {
        return 0
    }

    func (m *TokenCodec) DeprecatedInActingVersion() bool {
        return true
    }

    func (m *TokenCodec) DeprecatedEncodingOffset() uint {
        return 24
    }

    func (m *TokenCodec) DeprecatedNullValue() int32 {
        return int32(0)
    }

    func (m *TokenCodec) DeprecatedMinValue() int32 {
        return int32(-2147483647)
    }

    func (m *TokenCodec) DeprecatedMaxValue() int32 {
        return int32(2147483647)
    }

    func (m *TokenCodec) DeprecatedEncodingLength() int {
        return 4
    }

    func (m *TokenCodec) Deprecated() int32 {
        return Int32LittleEndian(m.buffer[(m.offset + 24):])
    }

    func (m *TokenCodec) SetDeprecated(value int32) *TokenCodec {
        PutInt32LittleEndian(m.buffer[(m.offset + 24):], value)
        return m
    }

func (m *TokenCodec) NameMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) NameCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) NameSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) NameInActingVersion() bool {
        return true
    }

func (m *TokenCodec) NameId() uint16 {
        return 11
    }

func (m *TokenCodec) NameHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) NameLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipName() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) Name() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetName(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutNameLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetNameAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetNameAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetNameAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutName(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutNameLen(str, uint16(len(str)))
}

func (m *TokenCodec) ConstValueMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) ConstValueCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) ConstValueSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) ConstValueInActingVersion() bool {
        return true
    }

func (m *TokenCodec) ConstValueId() uint16 {
        return 12
    }

func (m *TokenCodec) ConstValueHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) ConstValueLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipConstValue() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) ConstValue() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetConstValue(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutConstValueLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetConstValueAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetConstValueAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetConstValueAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutConstValue(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutConstValueLen(str, uint16(len(str)))
}

func (m *TokenCodec) MinValueMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) MinValueCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) MinValueSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) MinValueInActingVersion() bool {
        return true
    }

func (m *TokenCodec) MinValueId() uint16 {
        return 13
    }

func (m *TokenCodec) MinValueHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) MinValueLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipMinValue() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) MinValue() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetMinValue(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutMinValueLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetMinValueAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetMinValueAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetMinValueAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutMinValue(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutMinValueLen(str, uint16(len(str)))
}

func (m *TokenCodec) MaxValueMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) MaxValueCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) MaxValueSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) MaxValueInActingVersion() bool {
        return true
    }

func (m *TokenCodec) MaxValueId() uint16 {
        return 14
    }

func (m *TokenCodec) MaxValueHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) MaxValueLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipMaxValue() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) MaxValue() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetMaxValue(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutMaxValueLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetMaxValueAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetMaxValueAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetMaxValueAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutMaxValue(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutMaxValueLen(str, uint16(len(str)))
}

func (m *TokenCodec) NullValueMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) NullValueCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) NullValueSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) NullValueInActingVersion() bool {
        return true
    }

func (m *TokenCodec) NullValueId() uint16 {
        return 15
    }

func (m *TokenCodec) NullValueHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) NullValueLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipNullValue() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) NullValue() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetNullValue(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutNullValueLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetNullValueAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetNullValueAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetNullValueAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutNullValue(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutNullValueLen(str, uint16(len(str)))
}

func (m *TokenCodec) CharacterEncodingMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) CharacterEncodingCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) CharacterEncodingSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) CharacterEncodingInActingVersion() bool {
        return true
    }

func (m *TokenCodec) CharacterEncodingId() uint16 {
        return 16
    }

func (m *TokenCodec) CharacterEncodingHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) CharacterEncodingLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipCharacterEncoding() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) CharacterEncoding() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetCharacterEncoding(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutCharacterEncodingLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetCharacterEncodingAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetCharacterEncodingAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetCharacterEncodingAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutCharacterEncoding(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutCharacterEncodingLen(str, uint16(len(str)))
}

func (m *TokenCodec) EpochMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) EpochCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) EpochSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) EpochInActingVersion() bool {
        return true
    }

func (m *TokenCodec) EpochId() uint16 {
        return 17
    }

func (m *TokenCodec) EpochHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) EpochLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipEpoch() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) Epoch() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetEpoch(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutEpochLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetEpochAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetEpochAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetEpochAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutEpoch(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutEpochLen(str, uint16(len(str)))
}

func (m *TokenCodec) TimeUnitMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) TimeUnitCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) TimeUnitSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) TimeUnitInActingVersion() bool {
        return true
    }

func (m *TokenCodec) TimeUnitId() uint16 {
        return 18
    }

func (m *TokenCodec) TimeUnitHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) TimeUnitLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipTimeUnit() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) TimeUnit() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetTimeUnit(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutTimeUnitLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetTimeUnitAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetTimeUnitAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetTimeUnitAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutTimeUnit(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutTimeUnitLen(str, uint16(len(str)))
}

func (m *TokenCodec) SemanticTypeMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) SemanticTypeCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) SemanticTypeSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) SemanticTypeInActingVersion() bool {
        return true
    }

func (m *TokenCodec) SemanticTypeId() uint16 {
        return 19
    }

func (m *TokenCodec) SemanticTypeHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) SemanticTypeLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipSemanticType() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) SemanticType() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetSemanticType(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutSemanticTypeLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetSemanticTypeAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetSemanticTypeAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetSemanticTypeAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutSemanticType(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutSemanticTypeLen(str, uint16(len(str)))
}

func (m *TokenCodec) DescriptionMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) DescriptionCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) DescriptionSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) DescriptionInActingVersion() bool {
        return true
    }

func (m *TokenCodec) DescriptionId() uint16 {
        return 20
    }

func (m *TokenCodec) DescriptionHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) DescriptionLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipDescription() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) Description() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetDescription(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutDescriptionLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetDescriptionAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetDescriptionAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetDescriptionAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutDescription(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutDescriptionLen(str, uint16(len(str)))
}

func (m *TokenCodec) ReferencedNameMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) ReferencedNameCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) ReferencedNameSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) ReferencedNameInActingVersion() bool {
        return true
    }

func (m *TokenCodec) ReferencedNameId() uint16 {
        return 21
    }

func (m *TokenCodec) ReferencedNameHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) ReferencedNameLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipReferencedName() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) ReferencedName() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetReferencedName(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutReferencedNameLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetReferencedNameAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetReferencedNameAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetReferencedNameAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutReferencedName(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutReferencedNameLen(str, uint16(len(str)))
}

func (m *TokenCodec) PackageNameMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

func (m *TokenCodec) PackageNameCharacterEncoding() string {
        return "UTF-8"
    }

func (m *TokenCodec) PackageNameSinceVersion() uint64 {
        return 0
    }

func (m *TokenCodec) PackageNameInActingVersion() bool {
        return true
    }

func (m *TokenCodec) PackageNameId() uint16 {
        return 22
    }

func (m *TokenCodec) PackageNameHeaderLength() uint64 {
        return 2
}

func (m *TokenCodec) PackageNameLength() uint16 {
        return Uint16LittleEndian(m.buffer[m.SbePosition():])
}

    func (m *TokenCodec) SkipPackageName() uint64 {
        lengthOfLengthField := uint64(2)
        lengthPosition := m.SbePosition()
        dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition : lengthPosition+lengthOfLengthField]))
        m.SetSbePosition(lengthPosition + lengthOfLengthField + dataLength)
        return dataLength
    }

func (m *TokenCodec) PackageName() string {
    lengthFieldValue := uint64(Uint16LittleEndian(m.buffer[m.SbePosition():m.SbePosition()+2]))
    m.SetSbePosition(m.SbePosition() + uint64(2))
    pos := m.SbePosition()
    m.SetSbePosition(pos + lengthFieldValue)
    return string(m.buffer[pos:pos+lengthFieldValue])
}

func (m *TokenCodec) GetPackageName(dst []byte) int {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(m.SbePosition() + lengthOfLengthField)
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    bytesToCopy := dataLength
    if uint64(len(dst)) < dataLength {
        bytesToCopy = uint64(len(dst))
    }
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    copy(dst, m.buffer[pos:pos+bytesToCopy])
    return int(bytesToCopy)
}

func (m *TokenCodec) PutPackageNameLen(src string, length uint16) *TokenCodec {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    PutUint16LittleEndian(m.buffer[lengthPosition:], length)
    if length != uint16(0) {
        pos := m.SbePosition()
        m.SetSbePosition(pos + uint64(length))
        copy(m.buffer[pos:], src)
    }
    return m
}

func (m *TokenCodec) GetPackageNameAsString() string {
    lengthOfLengthField := uint64(2)
    lengthPosition := m.SbePosition()
    dataLength := uint64(Uint16LittleEndian(m.buffer[lengthPosition:lengthPosition+lengthOfLengthField]))
    m.SetSbePosition(lengthPosition + lengthOfLengthField)
    pos := m.SbePosition()
    m.SetSbePosition(pos + dataLength)
    return string(m.buffer[pos:pos+dataLength])
}

func (m *TokenCodec) GetPackageNameAsJsonEscapedString() string {
    oss := strings.Builder{}
    s := m.GetPackageNameAsString()

    for _, c := range s {
        switch c {
            case '"': oss.WriteString("\\\"")
            case '\\': oss.WriteString("\\\\")
            case '\b': oss.WriteString("\\b")
            case '\f': oss.WriteString("\\f")
            case '\n': oss.WriteString("\\n")
            case '\r': oss.WriteString("\\r")
            case '\t': oss.WriteString("\\t")

            default:
                if '\x00' <= c && c <= '\x1f' {
                    fmt.Fprintf(&oss, "%x", c)
                } else {
                    oss.WriteString(string(c))
                }
        }
    }

    return oss.String()
}

func (m *TokenCodec) PutPackageName(str string) *TokenCodec {
    if len(str) > 65534 {
        panic("string too long for length type [E109]")
    }
    return m.PutPackageNameLen(str, uint16(len(str)))
}

func (writer *TokenCodec) String() string {
    var builder strings.Builder
    builder.WriteString("{\"Name\": \"TokenCodec\", ")
    builder.WriteString(fmt.Sprintf("\"sbeTemplateId\": %d", writer.SbeTemplateId()))
    builder.WriteString(", ")

    builder.WriteString(`"tokenOffset": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.TokenOffset()))

    builder.WriteString(", ")
    builder.WriteString(`"tokenSize": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.TokenSize()))

    builder.WriteString(", ")
    builder.WriteString(`"fieldId": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.FieldId()))

    builder.WriteString(", ")
    builder.WriteString(`"tokenVersion": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.TokenVersion()))

    builder.WriteString(", ")
    builder.WriteString(`"componentTokenCount": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.ComponentTokenCount()))

    builder.WriteString(", ")
    builder.WriteString(`"signal": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.Signal()))

    builder.WriteString(", ")
    builder.WriteString(`"primitiveType": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.PrimitiveType()))

    builder.WriteString(", ")
    builder.WriteString(`"byteOrder": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.ByteOrder()))

    builder.WriteString(", ")
    builder.WriteString(`"presence": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.Presence()))

    builder.WriteString(", ")
    builder.WriteString(`"deprecated": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.Deprecated()))

    builder.WriteString(", ")
    builder.WriteString(`"name": `)
    builder.WriteString(`"` + writer.GetNameAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"constValue": `)
    builder.WriteString(`"` + writer.GetConstValueAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"minValue": `)
    builder.WriteString(`"` + writer.GetMinValueAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"maxValue": `)
    builder.WriteString(`"` + writer.GetMaxValueAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"nullValue": `)
    builder.WriteString(`"` + writer.GetNullValueAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"characterEncoding": `)
    builder.WriteString(`"` + writer.GetCharacterEncodingAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"epoch": `)
    builder.WriteString(`"` + writer.GetEpochAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"timeUnit": `)
    builder.WriteString(`"` + writer.GetTimeUnitAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"semanticType": `)
    builder.WriteString(`"` + writer.GetSemanticTypeAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"description": `)
    builder.WriteString(`"` + writer.GetDescriptionAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"referencedName": `)
    builder.WriteString(`"` + writer.GetReferencedNameAsJsonEscapedString() + `"`);

    builder.WriteString(", ")
    builder.WriteString(`"packageName": `)
    builder.WriteString(`"` + writer.GetPackageNameAsJsonEscapedString() + `"`);

    builder.WriteString("}")

    return builder.String()
}

func (m *TokenCodec) Skip() {
    m.SkipName()
    m.SkipConstValue()
    m.SkipMinValue()
    m.SkipMaxValue()
    m.SkipNullValue()
    m.SkipCharacterEncoding()
    m.SkipEpoch()
    m.SkipTimeUnit()
    m.SkipSemanticType()
    m.SkipDescription()
    m.SkipReferencedName()
    m.SkipPackageName()
}

func (m *TokenCodec) IsConstLength() bool {
    return false
}

func (m *TokenCodec) ComputeLength(
     NameLength int,
     ConstValueLength int,
     MinValueLength int,
     MaxValueLength int,
     NullValueLength int,
     CharacterEncodingLength int,
     EpochLength int,
     TimeUnitLength int,
     SemanticTypeLength int,
     DescriptionLength int,
     ReferencedNameLength int,
     PackageNameLength int) (int, error) {
    length := uint64(m.SbeBlockLength())

    length += m.NameHeaderLength()
    if m.NameLength() > 65534 {
        return 0, fmt.Errorf("NameLength too long for length type [E109]")
    }
    length += uint64(m.NameLength())

    length += m.ConstValueHeaderLength()
    if m.ConstValueLength() > 65534 {
        return 0, fmt.Errorf("ConstValueLength too long for length type [E109]")
    }
    length += uint64(m.ConstValueLength())

    length += m.MinValueHeaderLength()
    if m.MinValueLength() > 65534 {
        return 0, fmt.Errorf("MinValueLength too long for length type [E109]")
    }
    length += uint64(m.MinValueLength())

    length += m.MaxValueHeaderLength()
    if m.MaxValueLength() > 65534 {
        return 0, fmt.Errorf("MaxValueLength too long for length type [E109]")
    }
    length += uint64(m.MaxValueLength())

    length += m.NullValueHeaderLength()
    if m.NullValueLength() > 65534 {
        return 0, fmt.Errorf("NullValueLength too long for length type [E109]")
    }
    length += uint64(m.NullValueLength())

    length += m.CharacterEncodingHeaderLength()
    if m.CharacterEncodingLength() > 65534 {
        return 0, fmt.Errorf("CharacterEncodingLength too long for length type [E109]")
    }
    length += uint64(m.CharacterEncodingLength())

    length += m.EpochHeaderLength()
    if m.EpochLength() > 65534 {
        return 0, fmt.Errorf("EpochLength too long for length type [E109]")
    }
    length += uint64(m.EpochLength())

    length += m.TimeUnitHeaderLength()
    if m.TimeUnitLength() > 65534 {
        return 0, fmt.Errorf("TimeUnitLength too long for length type [E109]")
    }
    length += uint64(m.TimeUnitLength())

    length += m.SemanticTypeHeaderLength()
    if m.SemanticTypeLength() > 65534 {
        return 0, fmt.Errorf("SemanticTypeLength too long for length type [E109]")
    }
    length += uint64(m.SemanticTypeLength())

    length += m.DescriptionHeaderLength()
    if m.DescriptionLength() > 65534 {
        return 0, fmt.Errorf("DescriptionLength too long for length type [E109]")
    }
    length += uint64(m.DescriptionLength())

    length += m.ReferencedNameHeaderLength()
    if m.ReferencedNameLength() > 65534 {
        return 0, fmt.Errorf("ReferencedNameLength too long for length type [E109]")
    }
    length += uint64(m.ReferencedNameLength())

    length += m.PackageNameHeaderLength()
    if m.PackageNameLength() > 65534 {
        return 0, fmt.Errorf("PackageNameLength too long for length type [E109]")
    }
    length += uint64(m.PackageNameLength())

    return int(length), nil
}
