/* Generated SBE (Simple Binary Encoding) message codec */
// Code generated by SBE. DO NOT EDIT.

package uk_co_real_logic_sbe_ir_generated

import (
"fmt"
"math"
"strings"
)

type VarDataEncoding struct {
    buffer []byte
    bufferLength uint64
    offset uint64
    actingVersion uint64

}

    const (
        VarDataEncodingEncodedLength    uint64 = math.MaxUint64
        VarDataEncodingSbeSchemaID        uint16 = uint16(1)
        VarDataEncodingSbeSchemaVersion   uint16 = uint16(0)
    )

    func (m *VarDataEncoding) Wrap(
        buffer []byte,
        offset uint64,
        actingVersion uint64,
        bufferLength uint64) {
        m.buffer = buffer
        m.bufferLength = bufferLength
        m.offset = offset
        m.actingVersion = actingVersion
        if !SbeNoBoundsCheck && ((m.offset + math.MaxUint64) > m.bufferLength) {
            panic("buffer too short for flyweight [E107]")
        }
    }

    func (m *VarDataEncoding) EncodedLength() uint64 {
        return math.MaxUint64
    }

    func (m *VarDataEncoding) Offset() uint64 {
        return m.offset
    }

    func (m *VarDataEncoding) Buffer() []byte {
        return m.buffer
    }

    func (m *VarDataEncoding) BufferLength() uint64 {
        return m.bufferLength
    }

    func (m *VarDataEncoding) ActingVersion() uint64 {
        return m.actingVersion
    }

    func (m *VarDataEncoding) SbeSchemaId() uint16 {
        return uint16(1)
    }

    func (m *VarDataEncoding) SbeSchemaVersion() uint16 {
        return uint16(0)
    }

func (m *VarDataEncoding) LengthMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *VarDataEncoding) LengthId() int {
        return -1
    }

    func (m *VarDataEncoding) LengthSinceVersion() uint64 {
        return 0
    }

    func (m *VarDataEncoding) LengthInActingVersion() bool {
        return true
    }

    func (m *VarDataEncoding) LengthEncodingOffset() uint {
        return 0
    }

    func (m *VarDataEncoding) LengthNullValue() uint16 {
        return SbeNullValueUint16()
    }

    func (m *VarDataEncoding) LengthMinValue() uint16 {
        return uint16(0)
    }

    func (m *VarDataEncoding) LengthMaxValue() uint16 {
        return uint16(65534)
    }

    func (m *VarDataEncoding) LengthEncodingLength() int {
        return 2
    }

    func (m *VarDataEncoding) Length() uint16 {
        return Uint16LittleEndian(m.buffer[(m.offset + 0):])
    }

    func (m *VarDataEncoding) SetLength(value uint16) *VarDataEncoding {
        PutUint16LittleEndian(m.buffer[(m.offset + 0):], value)
        return m
    }

func (m *VarDataEncoding) VarDataMetaAttribute(metaAttribute string) string {
    switch metaAttribute {
        case "PRESENCE": return "required"
        default: return ""
    }
}

    func (m *VarDataEncoding) VarDataId() int {
        return -1
    }

    func (m *VarDataEncoding) VarDataSinceVersion() uint64 {
        return 0
    }

    func (m *VarDataEncoding) VarDataInActingVersion() bool {
        return true
    }

    func (m *VarDataEncoding) VarDataEncodingOffset() uint {
        return 2
    }

    func (m *VarDataEncoding) VarDataNullValue() uint8 {
        return SbeNullValueUint8()
    }

    func (m *VarDataEncoding) VarDataMinValue() uint8 {
        return uint8(0)
    }

    func (m *VarDataEncoding) VarDataMaxValue() uint8 {
        return uint8(254)
    }

    func (m *VarDataEncoding) VarDataEncodingLength() int {
        return -1
    }

func (writer *VarDataEncoding) String() string {
    builder := strings.Builder{}
    builder.WriteString("{")
    builder.WriteString(`"length": `)
    builder.WriteString(fmt.Sprintf(`"%v"`, writer.Length()))

    builder.WriteString("}")

    return builder.String()
}

